### PR TITLE
CentOS 7: Avoid SELinux protection (Error 503) with enforcing mode

### PR DESCRIPTION
**Pull request by syndrome5**
After the Linux installation, the 503 error appears (on CentOS 7).

To avoid this problem WITHOUT deactivate SELinux : 
1) Download the attached file [httpdPolicy.zip](https://github.com/RapidScada/scada/files/1837624/httpdPolicy.zip) and unzip it to get the .pp file
2) Launch this commandline : `semodule -i httpdPolicy.pp`
3) Reverify to set enforcing mode for SELinux & reboot

### CODE REVIEW

**Comment by 2mik** [comment]
> syndrome5 wants to merge 15 commits into master from develop
Hi,
I don't plan commit into master for now. Why you created such pull request?

**Comment by 2mik** [comment]
Could you create an issue instead of a pull request?

**Comment by syndrome5** [comment]
Done.

**Comment by 2mik** [comment]
Thank you. I will answer the issue.

**Pull request closed without merging**
