### PR TITLE
Save self signed certificate inside /usr/share/OPC Foundation

### PR DESCRIPTION
**Pull request by kumajaya**

### CODE REVIEW

**Comment by 2mik** [comment]
More info needed:

- What is the actual driver behavior?
- What behavior will be if we apply changes?
- Why we should change the configuration?

**Comment by kumajaya** [comment]
Solve "Cannot access certificate private key. Subject=CN=KpOpcUa, O=OPC Foundation, DC=my-machine-name" error on Ubuntu 20.04.1 LTS. We run RS as root, it make more sense to put certificate in /usr/share than /root/.local/share

**Comment by 2mik** [comment]
May be we should collect more statistics in different cases. All these settings were stored in the xml file to allow users to modify them according to the needs.

**Comment by 2mik** [comment]
According to the OPC UA references %CommonApplicationData% is for Windows. However, user can change the file in their own projects if it helps to solve an issue.

**Pull request closed without merging**
