### PR TITLE
I developed Modbus.dll to get bits from byte of holding registers

### PR DESCRIPTION
**Pull request by fmarslan**
how to use :

Step 1 : ElementGroup type selected Holding Registers
Step 2 : ElementType selected bool
Step 3 : We will write bitoffset value to Bit Offset Input Text

### CODE REVIEW

**Comment by fmarslan** [comment]
changed  with develop branch

**Comment by 2mik** [comment]
That's interesting!
Could you show some screenshots of the new features?

**Comment by fmarslan** [comment]
this approach use with modbus usually that I needed it

Example

one holding register(for example ushort) (this can uint32, long, etc.)
value : 0010000000101010

settings for declares for all bit
settings

Result
result

**Comment by 2mik** [comment]
Currently, this operation can be done by a formula in the configuration database. I agree that retrieving a bit in Communicator may be useful for a user to easily monitor data at testing phase. At the same time, if you decide to implement this feature, it is needed to make possible to extract all the bits from 16 bytes Modbus value. Because many devices provide some kind of flag register that contains many meaningful bits.

May be there should be a bit mask (like 0001000100010001) if ushort is chosen, and for each bit a separate tag is created.

I agree to merge the changes in the project if you would like to expand your idea and implement more general approach. In this case, it's better to start a new *.prj in VS, like KpModbusFlex (or other name you like). Use KpModbus.dll as a reference to avoid duplicating the code. And then it is ready and tested, create a pull request in [this special repository](https://github.com/RapidScada/scada-community). We could discuss the development on https://forum.rapidscada.org/ There are many users who can give valuable advice.

**Comment by 2mik** [comment]
[The community Rapid SCADA repository](https://github.com/RapidScada/scada-community) is a good place to play and test new ideas whether they are useful for many people or for a single case.

**Comment by 2mik** [comment]
@fmarslan , if you could share Turkish localization of the Webstation app, this would be nice. Many people from Turkey download Rapid SCADA.

**Comment by fmarslan** [comment]
I observed this solution some apps and providing easy tag define also  u are right we could discuss the development but I had a urgent need this solution and when I research all suggestions, everyone suggested formulas. my need is be to easily monitor data at testing phase so I developed this solution.

I want committed for other people use it

If you want, I can  create new project but my suggestion is single project because this approach use often.

I can share the Turkish localization of the Webstation application at  convenient time

**Comment by 2mik** [comment]
> I'm using RapidScada in a big project

Could you tell little more about the project?

**Comment by fmarslan** [comment]
> Could you tell little more about the project?

sorry I cannot tell more about project due to company rules

> Do you use WCF or other technique for REST API? Will it work on Linux by Mono?

No problem! because I'm using ubuntu OS on server

> Yes, please create a project and pull it to https://github.com/RapidScada/scada-community

I will close this PR and create new PR

**Pull request closed without merging**
